### ISSUE TITLE
Empty file generated

### ISSUE THREAD

**Issue by nngakosso** [FIXTradingCommunity/tablature#13]
Hello I was testing the tool with your executables on jdk14 and while the program where running, It was generating empty files for md2orchestra. Any idea of what it could be?  since I got no error whatsoever.

Thanks.

**Comment by donmendelson** [comment]
@nngakosso can you share your file so I can test?

**Comment by nngakosso** [comment]
I think you already have it I just tried with what Florian produced from log2orchestra. That's why I think I have something off.

**Comment by donmendelson** [comment]
Please retry with latest version after project rename. If there is still an problem, re-enter a detailed issue.
