### ISSUE TITLE
Additional column for Components

### ISSUE THREAD

**Issue by jimnup** [FIXTradingCommunity/tablature#24]
Components can have subcomponents and those subcomponents may have a scenario specialization. The documentation doesn't show the scenario column available for components. Was wondering if this is a functionality issue or a documentation issue?

**Comment by donmendelson** [comment]
Yes, a component can have a scenario. A markdown header for it would be in format
```
## Component Instrument scenario fx
```
A reference to that component as a message member would include
```
| Name         | Scenario |
|--------------|----------|
| Instrument   | fx       |
```
