### ISSUE TITLE
[md2orchestra] not finding markdown files by relative path on Linux

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/tablature#45]
md2orchestra takes a filename pattern for markdown input files. This supports wildcards like *.md in a directory to read multiple files.  It was reported that a relative path for the directory fails to find the desired files on Ubuntu Linux, but an absolute path does work.

**Comment by donmendelson** [comment]
One of the options in walking a directory tree to find matching files is whether symbolic links should be followed. I'm assuming it should unless someone objects.

**Comment by donmendelson** [comment]
Two changes were made in file search that may improve usage:
* The file matcher is now configured to follow symbolic links; it wasn't before.
* No limit on directory depth; before it only looked one level deep.

I have successfully tested revised code on Windows and Linux, but users may have other cases to test.

**Comment by JThoennes** [comment]
@donmendelson Although this issue is closed I found that 
```
md2orchestra ./file.xml
```
works but
```
md2orchestra file.xml
```
does not work. Tested on MacOS. Probably also applies to `orchestra2md`.

**Comment by JThoennes** [comment]
@donmendelson IMHO, the feature with the pattern matching looking for files looks "Windows-ish" or "Ant-ish" to me :-)
I would rather drop it in favor of explicit file names as in UNIX.

But your mileage may vary as well as that of @kleihan ;-)

**Comment by JThoennes** [comment]
Also happens on Linux:
```
$ md2orchestra -o my-fix-orchestra-V.xml -r reference/OrchestraFIXLatest.xml my-fix-orchestra.md
2022-10-13 18:36:47,474 INFO : io.fixprotocol.md2orchestra.Md2Orchestra version 1.0.2-SNAPSHOT
2022-10-13 18:36:48,361 INFO : Md2Orchestra searching for input at path . file name pattern my-fix-orchestra.md
2022-10-13 18:36:48,365 INFO : Md2Orchestra matched 0 file(s)
2022-10-13 18:36:48,400 INFO : Md2Orchestra output written
```
