### ISSUE TITLE
Support conditionally required members of a message or component

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/tablature#5]
In an Orchestra XML file, a rule element may alter presence to tell when a field or component is required. The orchestra2md should output the member as conditionally required, and md2orchestra should recognized an easy syntax for this purpose.

**Comment by donmendelson** [comment]
Proposed format for assignment and rule elements of a fieldRef.

1. Assigns the value of a field of ExecutionReport to echo the value from incoming order.

Keyword "assign".

| Name                        | Tag       | Presence | Values                |
|-----------------------------|-----------|----------|-----------------------|
| StandardHeader              | component | required |                       |
| ApplicationSequenceControl  | component | optional |                       |
| OrderID                     | 37        | required |                       |
| ClOrdID                     | 11        | optional | assign in.ClOrdID     |

2. Conditionally required field when an expression is true.

Keyword "when" followed by Score DSL expression. Note: &#124;&#124; symbol for logical or must be escaped within a markdown table.

| Name                       | Tag       | Presence                                                |
|----------------------------|-----------|---------------------------------------------------------|
| OrdType                    | 40        | required                                                |
| PriceType                  | 423       | optional                                                |
| Price                      | 44        | optional                                                |
| PriceProtectionScope       | 1092      | optional                                                |
| StopPx                     | 99        | required when OrdType == ^Stop &#124;&#124; OrdType == ^StopLimit |

**Comment by jimnup** [comment]
Don - this looks good - your approach looks good.

**Comment by jimnup** [comment]
Actually the markdown renders quite well and is highly readable on GitHub. Cool we are moving toward the markdown and open stacks in terms of development tools.

**Comment by donmendelson** [comment]
The utilities md2orchestra and orchestra2md will not evaluate the DSL expressions. That step should be performed on the Orchestra file using RepositoryValidator.
